### ISSUE TITLE
Error when trying to load ad.

### ISSUE THREAD

**Issue by rjbruneel** [rdlabo-team/capacitor-admob#14]
When I run the following code:

  private options: AdOptions = {
    adId: 'ca-app-pub-[my-id]',
    adSize: AdSize.BANNER,
    position: AdPosition.BOTTOM_CENTER,
    margin: 0
  };

    AdMob.showBanner(this.options);

    // Subscribe Banner Event Listener
    AdMob.addListener('onAdLoaded', (info: boolean) => {
      alert('Banner Ad Loaded');
    });

    AdMob.addListener('onAdFailedToLoad', (error) => {
      alert(JSON.stringify(error));
    });

The ad doesn't load and I get the following message in the debugger log: "I/Ads: Ad failed to load : 1".

Any help troubleshooting the issue would be greatly appreciated.

**Comment by rdlabo** [comment]
Maybe mistake ID settings:
https://stackoverflow.com/questions/38835738/failed-to-load-ad-error-1/47295234

**Comment by rjbruneel** [comment]
That was the issue. After fixing that issue I got errorCode 0 which occurs when the app is in development mode or the add id is very new. Google has an app id for testing in dev mode which worked for me: ca-app-pub-3940256099942544/6300978111 Thank you for developing this and for the help resolving my issue.
